[package]
name = "reaccionar"
version = "0.1.0"
authors = ["Ian Reese <kalissaac@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8"
dotenv = "0.15.0"